class AppLocalizationsEn {
  AppLocalizationsEn._();

  static const Map<String, String> strings = {
    'appName': 'BreadBoard AI',
    'appTagline': 'Build Circuits with Voice',
    'login': 'Login',
    'register': 'Register',
    'logout': 'Logout',
    'email': 'Email',
    'password': 'Password',
    'confirmPassword': 'Confirm Password',
    'forgotPassword': 'Forgot Password',
    'home': 'Home',
    'voice': 'Voice',
    'circuits': 'Circuits',
    'marketplace': 'Marketplace',
    'profile': 'Profile',
    'settings': 'Settings',
    'search': 'Search',
    'cancel': 'Cancel',
    'save': 'Save',
    'delete': 'Delete',
    'edit': 'Edit',
    'submit': 'Submit',
    'loading': 'Loading...',
    'errorOccurred': 'An error occurred',
    'retry': 'Retry',
    'noInternet': 'No internet connection',
    'darkMode': 'Dark Mode',
    'lightMode': 'Light Mode',
    'systemMode': 'System Mode',
    'language': 'Language',
    'english': 'English',
    'hindi': 'हिन्दी',
    'rajasthani': 'राजस्थानी',
    'circuitGeneration': 'Circuit Generation',
    'circuitLearning': 'Circuit Learning',
    'repairAssistant': 'Repair Assistant',
    'breadboardVerification': 'Breadboard Verification',
    'componentDetection': 'Component Detection',
    'projectHistory': 'Project History',
    'costEstimation': 'Cost Estimation',
    'safetyValidation': 'Safety Validation',
    'startVoiceInput': 'Start Voice Input',
    'stopVoiceInput': 'Stop Voice Input',
    'speakNow': 'Speak now...',
    'processing': 'Processing...',
    'welcome': 'Welcome',
    'getStarted': 'Get Started',
    'skip': 'Skip',
    'next': 'Next',
  };
}
