class AppLocalizationsRaj {
  AppLocalizationsRaj._();

  static const Map<String, String> strings = {
    'appName': 'ब्रेडबोर्ड AI',
    'appTagline': 'आवाज़ सै सर्किट बणावैं',
    'login': 'लॉगिन',
    'register': 'रजिस्टर',
    'logout': 'लॉगआउट',
    'email': 'ईमेल',
    'password': 'पासवर्ड',
    'confirmPassword': 'पासवर्ड की पुष्टि करो',
    'forgotPassword': 'पासवर्ड भूल ग्या',
    'home': 'घर',
    'voice': 'आवाज़',
    'circuits': 'सर्किट',
    'marketplace': 'बाज़ार',
    'profile': 'प्रोफ़ाइल',
    'settings': 'सेटिंग्स',
    'search': 'खोजो',
    'cancel': 'रद्द करो',
    'save': 'राखो',
    'delete': 'मेटाओ',
    'edit': 'बदलो',
    'submit': 'जमा करो',
    'loading': 'लोड हो रह्यो है...',
    'errorOccurred': 'कोई त्रुटि हो गी',
    'retry': 'फेर प्रयास करो',
    'noInternet': 'इंटरनेट कनेक्शन नीं है',
    'darkMode': 'डार्क मोड',
    'lightMode': 'लाइट मोड',
    'systemMode': 'सिस्टम मोड',
    'language': 'भाषा',
    'english': 'अंग्रेज़ी',
    'hindi': 'हिन्दी',
    'rajasthani': 'राजस्थानी',
    'circuitGeneration': 'सर्किट जनरेशन',
    'circuitLearning': 'सर्किट सीखो',
    'repairAssistant': 'मरम्मत सहायक',
    'breadboardVerification': 'ब्रेडबोर्ड जांच',
    'componentDetection': 'कम्पोनेंट पहचान',
    'projectHistory': 'प्रोजेक्ट इतिहास',
    'costEstimation': 'लागत अनुमान',
    'safetyValidation': 'सुरक्षा जांच',
    'startVoiceInput': 'आवाज़ इनपुट शुरू करो',
    'stopVoiceInput': 'आवाज़ इनपुट बंद करो',
    'speakNow': 'अब बोलो...',
    'processing': 'प्रोसेस हो रह्यो है...',
    'welcome': 'स्वागत है',
    'getStarted': 'शुरू करो',
    'skip': 'छोड़ो',
    'next': 'अगलो',
  };
}
