class AppLocalizationsHi {
  AppLocalizationsHi._();

  static const Map<String, String> strings = {
    'appName': 'ब्रेडबोर्ड AI',
    'appTagline': 'आवाज़ से सर्किट बनाएं',
    'login': 'लॉगिन',
    'register': 'रजिस्टर',
    'logout': 'लॉगआउट',
    'email': 'ईमेल',
    'password': 'पासवर्ड',
    'confirmPassword': 'पासवर्ड की पुष्टि करें',
    'forgotPassword': 'पासवर्ड भूल गए',
    'home': 'होम',
    'voice': 'आवाज़',
    'circuits': 'सर्किट',
    'marketplace': 'बाज़ार',
    'profile': 'प्रोफ़ाइल',
    'settings': 'सेटिंग्स',
    'search': 'खोजें',
    'cancel': 'रद्द करें',
    'save': 'सहेजें',
    'delete': 'हटाएं',
    'edit': 'संपादित करें',
    'submit': 'जमा करें',
    'loading': 'लोड हो रहा है...',
    'errorOccurred': 'एक त्रुटि हुई',
    'retry': 'पुनः प्रयास करें',
    'noInternet': 'कोई इंटरनेट कनेक्शन नहीं',
    'darkMode': 'डार्क मोड',
    'lightMode': 'लाइट मोड',
    'systemMode': 'सिस्टम मोड',
    'language': 'भाषा',
    'english': 'अंग्रेज़ी',
    'hindi': 'हिन्दी',
    'rajasthani': 'राजस्थानी',
    'circuitGeneration': 'सर्किट जनरेशन',
    'circuitLearning': 'सर्किट लर्निंग',
    'repairAssistant': 'मरम्मत सहायक',
    'breadboardVerification': 'ब्रेडबोर्ड जांच',
    'componentDetection': 'कम्पोनेंट पहचान',
    'projectHistory': 'प्रोजेक्ट इतिहास',
    'costEstimation': 'लागत अनुमान',
    'safetyValidation': 'सुरक्षा जांच',
    'startVoiceInput': 'आवाज़ इनपुट शुरू करें',
    'stopVoiceInput': 'आवाज़ इनपुट बंद करें',
    'speakNow': 'अब बोलें...',
    'processing': 'प्रोसेस हो रहा है...',
    'welcome': 'स्वागत है',
    'getStarted': 'शुरू करें',
    'skip': 'छोड़ें',
    'next': 'अगला',
  };
}
