"""Generate additional circuit entries for the circuit library."""
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

CIRCUITS = [
    # Audio Circuits
    ("Simple Audio Amplifier using LM386", "Build a low-power audio amplifier using LM386 IC for small speakers and headphones.", ["LM386 Audio Amplifier IC", "Resistor 10kΩ", "Capacitor 10µF (2x)", "Capacitor 100µF", "Capacitor 0.1µF", "Speaker 8Ω", "Potentiometer 10kΩ", "3.5mm Audio Jack", "9V Battery", "Breadboard", "Jumper wires"], ["Connect LM386 pin 1 to pin 8 via 10µF capacitor for gain of 200", "Pin 2 and pin 4 to GND", "Pin 3 to audio input via 10µF capacitor and 10kΩ potentiometer", "Pin 5 to 100µF capacitor positive leg, negative to speaker", "Pin 6 to 9V positive", "Pin 7 to GND via 0.1µF capacitor", "Add 10kΩ resistor from pin 3 to GND"], "The LM386 is a low-voltage audio amplifier with fixed gain of 20 (or 200 with pin 1-8 capacitor). The input signal is AC-coupled through the capacitor while the potentiometer controls volume. The output drives an 8Ω speaker through a coupling capacitor that blocks DC."),
    ("Passive Tone Control Circuit", "A simple bass and treble control circuit using RC filters for audio applications.", ["Resistor 100kΩ (2x)", "Resistor 10kΩ (2x)", "Capacitor 0.1µF (2x)", "Capacitor 0.01µF", "Potentiometer 100kΩ (2x)", "Audio input jack", "Audio output jack", "Breadboard", "Jumper wires"], ["Connect input signal to first 100kΩ resistor", "For bass control: 100kΩ pot with 0.1µF capacitor to GND", "For treble control: 10kΩ pot with 0.01µF capacitor in series", "Connect mid-point of bass pot to treble section through 100kΩ resistor", "Output from treble section through 10kΩ resistor", "Use shielded audio cables for input and output"], "RC filter networks selectively attenuate or boost frequency ranges. The bass section uses a low-pass filter (100kΩ + 0.1µF, cutoff ~16Hz) while treble uses a high-pass filter (10kΩ + 0.01µF, cutoff ~1.6kHz)."),
    ("Microphone Preamplifier Circuit", "Electret microphone preamplifier using transistor for clear voice pickup.", ["Electret Microphone", "NPN Transistor BC547", "Resistor 10kΩ", "Resistor 100kΩ", "Resistor 2.2kΩ", "Capacitor 10µF (2x)", "Capacitor 100µF", "5V Power Supply", "Breadboard", "Jumper wires"], ["Connect microphone positive to 5V through 10kΩ resistor", "Microphone output to BC547 base through 10µF capacitor", "BC547 collector to 5V through 2.2kΩ resistor", "BC547 emitter to GND", "100kΩ resistor from base to 5V (bias)", "Output from collector through 10µF capacitor", "100µF capacitor across power supply"], "The electret microphone requires a bias voltage (provided by 10kΩ resistor). The BC547 transistor amplifies the small audio signal. The 100kΩ resistor sets the operating point. Output is AC-coupled for connection to audio amplifiers."),
    # Power Supply Circuits
    ("Variable Voltage Power Supply using LM317", "Adjustable voltage regulator circuit from 1.25V to 37V using LM317.", ["LM317 Voltage Regulator", "Resistor 240Ω", "Potentiometer 10kΩ", "Capacitor 0.1µF", "Capacitor 1µF", "Capacitor 10µF", "Heat Sink", "Transformer 12-0-12V", "Diode 1N4007 (4x)", "Breadboard", "Jumper wires"], ["Build bridge rectifier using 4x 1N4007 diodes", "Connect transformer secondary to bridge AC inputs", "Bridge output (+) to LM317 input (pin 3)", "LM317 adjust (pin 1) to 240Ω resistor to GND", "10kΩ potentiometer between adjust pin and GND", "0.1µF capacitor from input pin to GND", "1µF capacitor from output pin (pin 2) to GND", "10µF capacitor from adjust to GND", "Mount LM317 on heat sink"], "The LM317 maintains 1.25V between output and adjust pins. The output voltage is Vout = 1.25 × (1 + R2/240). With 10kΩ pot, output ranges from 1.25V to about 28V depending on input voltage."),
    ("5V Power Supply using 7805", "Regulated 5V DC power supply from AC mains using 7805 voltage regulator.", ["Transformer 9-0-9V, 500mA", "Diode 1N4007 (4x)", "Capacitor 1000µF 25V", "Capacitor 0.33µF", "Capacitor 0.1µF", "7805 Voltage Regulator", "Heat Sink", "Fuse 500mA", "Power cord", "Breadboard", "Jumper wires"], ["Connect fuse to AC mains live wire", "Transformer primary to mains through fuse", "Build bridge rectifier with 4x 1N4007 diodes", "Capacitor 1000µF across rectifier output (polarity correct)", "7805 input to rectifier positive, GND to negative", "0.33µF capacitor from 7805 input to GND", "0.1µF capacitor from 7805 output to GND", "Mount 7805 on heat sink"], "The transformer steps down 230V AC to 9V AC. The bridge rectifier converts to pulsating DC, and 1000µF capacitor filters it. The 7805 regulator provides clean 5V output rated up to 1A. Output capacitors improve transient response."),
    ("Dual Polarity Power Supply (±12V)", "Split power supply providing +12V and -12V from single transformer.", ["Transformer 12-0-12V, 1A", "Diode 1N4007 (4x)", "Capacitor 1000µF (2x)", "Capacitor 0.33µF (2x)", "Capacitor 0.1µF (2x)", "7812 Voltage Regulator", "7912 Voltage Regulator", "Heat Sinks (2x)", "Fuse 1A", "Breadboard"], ["Connect transformer center tap to GND", "Bridge rectifier from outer secondary wires", "1000µF capacitor from +DC to GND", "1000µF capacitor from GND to -DC", "7812 input to +DC, GND pin to system GND", "7912 GND pin to system GND, input to -DC", "Capacitors 0.33µF on both regulator inputs", "Capacitors 0.1µF on both regulator outputs", "Mount both regulators on heat sinks"], "The center-tapped transformer with bridge rectifier creates both positive and negative DC rails. 7812 regulates +12V and 7912 regulates -12V. This supply is essential for op-amp circuits requiring dual supply voltages."),
    ("Battery Charger Circuit for Li-Ion", "Constant current/constant voltage charger for single Li-Ion cells using TP4056.", ["TP4056 Charging Module", "Li-Ion Battery 3.7V", "Resistor 1.2kΩ (programs 1A charge)", "LED Red (charging indicator)", "LED Blue (full indicator)", "Capacitor 10µF", "Capacitor 0.1µF", "5V Power Supply (USB)", "Battery holder", "PCB"], ["Connect 5V input to TP4056 IN+ and IN-", "Add 10µF and 0.1µF capacitors across input", "Set charge current with 1.2kΩ resistor on PROG pin", "Connect battery to BAT+ and BAT- terminals", "Red LED to CHRG pin via 1kΩ resistor", "Blue LED to STDBY pin via 1kΩ resistor", "Ensure proper polarity on battery connections"], "TP4056 charges Li-Ion batteries with CC/CV profile: 1A constant current until 4.2V, then constant voltage with decreasing current. The PROG resistor sets charge current (1.2kΩ = 1A). Red LED glows during charging, blue indicates full charge."),
    # Sensor & Measurement
    ("Digital Thermometer using LM35", "Precise temperature measurement circuit using LM35 sensor and ADC.", ["LM35 Temperature Sensor", "Arduino Uno", "16x2 LCD Display", "Resistor 10kΩ (for contrast)", "Potentiometer 10kΩ (LCD contrast)", "Breadboard", "Jumper wires", "5V Power Supply"], ["Connect LM35 VCC to 5V, GND to GND", "LM35 output to Arduino A0", "LCD RS to Arduino pin 12", "LCD E to pin 11", "LCD D4 to pin 5, D5 to pin 4, D6 to pin 3, D7 to pin 2", "10kΩ pot for contrast on LCD pin 3", "Read analog value: tempC = (analogRead(A0) * 5.0 / 1024.0) * 100", "Display temperature on LCD using LiquidCrystal library"], "LM35 outputs 10mV per °C (250mV at 25°C). Arduino reads analog voltage and converts to temperature. LCD displays in Celsius. Accuracy is ±0.5°C at room temperature. The sensor can measure from -55°C to 150°C."),
    ("Ultrasonic Distance Meter using HC-SR04", "Measure distance using ultrasonic sensor HC-SR04 with Arduino and display.", ["HC-SR04 Ultrasonic Sensor", "Arduino Uno", "16x2 LCD Display", "Resistor 330Ω", "Resistor 470Ω (voltage divider for echo)", "Breadboard", "Jumper wires"], ["HC-SR04 VCC to 5V, GND to GND", "Trig pin to Arduino pin 9", "Echo pin to Arduino pin 10", "Voltage divider: 330Ω + 470Ω on echo line (optional)", "LCD connections as standard", "Send 10µs pulse to Trig", "Read pulse duration on Echo", "Distance = duration × 0.034 / 2 in cm"], "HC-SR04 sends ultrasonic burst (40kHz) and measures echo return time. Sound speed is 343 m/s. Distance = (time × speed)/2. Range: 2cm to 400cm with ±3mm accuracy. The voltage divider protects Arduino pin from 5V echo signal."),
    ("Digital Voltmeter using ICL7107", "Precision 3.5 digit voltmeter using ICL7107 ADC with 7-segment display.", ["ICL7107 ADC IC", "7-Segment LED Display (3.5 digit)", "Resistor 47kΩ", "Resistor 1MΩ", "Resistor 100kΩ", "Capacitor 0.22µF", "Capacitor 0.1µF", "Capacitor 0.47µF", "Potentiometer 10kΩ (calibration)", "5V Power Supply"], ["ICL7107 pin 1 to 5V, pin 21 to GND", "Reference: pin 36 through 47kΩ to 5V", "47kΩ + 1MΩ voltage divider on input (pin 30-31)", "0.22µF on pin 27-28 (integrator)", "0.47µF on pin 29 to GND (auto-zero)", "100kΩ + 0.1µF on pin 33-34 (clock)", "Connect segment display to pins 2-19", "Calibrate with 10kΩ pot on reference"], "ICL7107 is a 3.5-digit ADC with direct 7-segment drivers. It uses dual-slope conversion for high noise rejection. Resolution is 0.05% (2000 counts). Input range is ±200mV without divider, or higher with external voltage divider. Common for DIY multimeters."),
    # RF & Wireless
    ("FM Transmitter Circuit", "Simple FM transmitter broadcasting on 88-108MHz band using transistor.", ["NPN Transistor 2N3904", "Electret Microphone", "Resistor 10kΩ (2x)", "Resistor 100Ω", "Capacitor 10pF", "Capacitor 100pF", "Capacitor 4.7pF", "Capacitor 0.1µF", "Inductor 5 turns of 22AWG on 5mm former", "Trimmer Capacitor 5-20pF", "Antenna (30cm wire)", "3V Battery", "Breadboard"], ["Wind 5-turn inductor on 5mm former (0.5µH)", "Connect transistor base to 100pF capacitor to inductor", "100Ω from collector to 3V positive", "10kΩ from collector to base (feedback)", "Microphone to base through 0.1µF and 10kΩ", "10pF capacitor from inductor to antenna", "Trimmer capacitor parallel to inductor", "4.7pF from collector to inductor tap"], "The transistor oscillates at FM band frequency (88-108MHz) determined by LC tank (inductor + trimmer). Audio from microphone frequency-modulates the oscillator by varying base capacitance (varactor effect). Range is about 50-100 meters. Use trimmer to adjust frequency to clear channel."),
    ("Simple Radio Receiver (Crystal Set)", "Basic AM radio receiver using a germanium diode and tuned LC circuit.", ["Germanium Diode 1N34A", "Inductor 100µH (ferrite rod antenna)", "Variable Capacitor 365pF", "Resistor 100kΩ", "Capacitor 0.01µF", "Piezoelectric Earphone (high impedance)", "Antenna wire (10-20m long)", "Ground rod"], ["Connect ferrite rod antenna coil to variable capacitor (parallel LC)", "1N34A diode anode to LC tank top", "Diode cathode to 100kΩ resistor", "0.01µF capacitor from resistor to GND", "Piezo earphone across the 0.01µF capacitor", "Antenna wire to LC tank top (via 100pF if needed)", "Ground rod to circuit GND", "Tune variable capacitor for different stations"], "The LC tank resonates at the desired AM frequency (530-1600kHz). The germanium diode rectifies the modulated RF signal, extracting the audio. The capacitor + resistor filter removes RF carrier. Requires good antenna and ground for strong reception. No batteries needed - runs on radio wave energy."),
    ("RF Remote Control using 433MHz", "Wireless on/off control using 433MHz RF modules and HT12D/E encoder-decoder.", ["433MHz RF Transmitter Module", "433MHz RF Receiver Module", "HT12E Encoder IC", "HT12D Decoder IC", "Resistor 1MΩ (oscillator)", "Resistor 51kΩ (oscillator)", "Push buttons (4x)", "LEDs (4x)", "Resistor 220Ω (4x)", "9V Battery (2x)", "Breadboards (2x)"], ["Transmitter side: HT12E pins 1-8 as address/data", "HT12E pin 15 to 1MΩ resistor to GND", "HT12E pin 14 to RF transmitter DATA", "Push buttons from pins 10-13 to GND", "Receiver side: RF receiver DATA to HT12D pin 14", "HT12D pin 15 to 51kΩ resistor to GND", "HT12D pins 10-13 to 220Ω resistors to LEDs", "LEDs to GND", "Match address pins (1-8) on both ICs"], "HT12E converts parallel data (button presses) to serial, which the RF module transmits at 433MHz. HT12D decodes serial back to parallel outputs. Each button controls one output LED. Range is about 50-100 meters in open air. The 1MΩ and 51kΩ resistors set internal oscillator frequencies for encoder and decoder respectively."),
    # Motor Control
    ("DC Motor Speed Controller using PWM", "Motor speed control using 555 timer PWM generator and MOSFET driver.", ["555 Timer IC", "IRFZ44N N-Channel MOSFET", "Diode 1N4007 (flyback)", "Potentiometer 100kΩ (speed control)", "Resistor 1kΩ", "Resistor 10kΩ", "Capacitor 0.1µF", "Capacitor 10µF", "DC Motor (6-12V)", "12V Power Supply", "Breadboard"], ["Wire 555 as astable: pin 8 and 4 to VCC, pin 1 to GND", "Pin 7 to 10kΩ to VCC, pin 7 to 1kΩ to pin 6", "100kΩ pot between pin 6 and pin 2", "0.1µF from pin 2 to GND", "555 output (pin 3) to MOSFET gate via 1kΩ", "MOSFET drain to motor, source to GND", "Flyback diode across motor (cathode to motor +)", "Capacitor 10µF across power supply"], "555 timer generates PWM signal at ~7kHz. The potentiometer varies duty cycle from 0% to 100% by changing the charge/discharge time ratio. The MOSFET switches the motor at high frequency, and average motor voltage = duty cycle × supply voltage. The flyback diode protects the MOSFET from inductive spikes."),
    ("Stepper Motor Driver using ULN2003", "Drive unipolar stepper motor using ULN2003 Darlington array.", ["28BYJ-48 Stepper Motor (5V)", "ULN2003 Driver Board", "Arduino Uno", "Potentiometer 10kΩ (speed control)", "Push button (direction)", "10kΩ pull-up resistor", "5V Power Supply", "Breadboard", "Jumper wires"], ["Connect stepper motor to ULN2003 board", "ULN2003 IN1 to Arduino pin 8", "IN2 to pin 9, IN3 to pin 10, IN4 to pin 11", "ULN2003 GND to Arduino GND, VCC to 5V", "Potentiometer wiper to Arduino A0", "Push button to Arduino pin 2 with 10kΩ pull-up", "Use Stepper.h library with 2048 steps/revolution", "Speed from pot: map(analogRead(A0), 0, 1023, 5, 20) RPM"], "The 28BYJ-48 is a 5V unipolar stepper with 2048 steps per revolution (reduction gearbox). ULN2003 provides current amplification (500mA per channel). Sequence: IN1-IN2-IN3-IN4 in wave drive or half-step mode for smoother rotation. Speed controlled by step delay."),
    ("Servo Motor Tester Circuit", "Simple servo motor tester using 555 timer to generate PWM control signal.", ["555 Timer IC", "Servo Motor (SG90)", "Potentiometer 10kΩ (position control)", "Resistor 1kΩ", "Resistor 10kΩ (2x)", "Diode 1N4148 (2x)", "Capacitor 0.1µF", "Capacitor 10µF", "5V Power Supply", "Breadboard"], ["Wire 555 as astable with diodes for independent charge/discharge", "1kΩ + pot to pin 7 (charge path through D1)", "10kΩ to pin 7 discharge through D2", "0.1µF from pin 2 to GND", "Pin 3 output to servo control wire (white/orange)", "Servo red to 5V, brown/black to GND", "10µF capacitor across servo power", "Pot adjusts pulse width from 1ms to 2ms"], "Servo position is controlled by pulse width: 1ms = 0°, 1.5ms = 90°, 2ms = 180°. The 555 generates a ~50Hz signal (20ms period). Diodes allow independent adjustment of charge and discharge times through the potentiometer, varying the duty cycle while maintaining frequency."),
    ("Bidirectional Motor Control using H-Bridge", "Control DC motor forward/reverse using L293D H-Bridge IC.", ["L293D Motor Driver IC", "DC Motor (6-12V)", "Arduino Uno", "Push buttons (3x: forward, reverse, stop)", "Resistor 10kΩ (3x, pull-down)", "Diode 1N4007 (4x, flyback)", "Capacitor 0.1µF", "12V Power Supply", "Breadboard"], ["L293D pin 1 (enable) to 5V", "Input pins: pin 2 to Arduino D8, pin 7 to D9", "Output pins: pin 3 to motor terminal 1, pin 6 to motor terminal 2", "L293D VCC (pin 16) to 5V, VS (pin 8) to 12V", "GND pins (4,5,12,13) to common GND", "Flyback diodes from each motor terminal to VS and GND", "Buttons to Arduino D2 (forward), D3 (reverse), D4 (stop)", "0.1µF capacitor across power supply"], "L293D is a dual H-bridge motor driver (1A per channel). For one motor: input 1 high + input 2 low = forward; reverse for opposite; both low = stop. The enable pin (connected to 5V) keeps the driver always active. Flyback diodes protect against motor inductive spikes."),
    # Digital Logic
    ("Binary Counter using 74LS93", "4-bit binary counter circuit displaying count on LEDs using 7493 IC.", ["74LS93 4-bit Binary Counter", "Resistor 330Ω (4x)", "LED (4x, different colors)", "Push button (clock)", "Resistor 10kΩ (pull-up)", "Capacitor 0.1µF (debounce)", "5V Power Supply", "Breadboard", "Jumper wires"], ["74LS93 pin 5 (VCC) to 5V, pin 10 (GND) to GND", "Clock input (pin 14) to push button through 10kΩ pull-up", "0.1µF capacitor from clock pin to GND (debounce)", "Output QA (pin 12) to first LED via 330Ω", "Output QB (pin 9) to second LED via 330Ω", "Output QC (pin 8) to third LED via 330Ω", "Output QD (pin 11) to fourth LED via 330Ω", "Connect pin 12 to pin 1 (internal divide-by-8 mode)", "All LED cathodes to GND"], "The 74LS93 is a 4-bit binary counter that counts from 0 to 15 (0000 to 1111). Each press of the button increments the count. LEDs display the binary value: QD (MSB) to QA (LSB). The RC network debounces the push button to prevent multiple counts from mechanical bounce."),
    ("7-Segment Display Counter using 4026", "Count from 0-9 on 7-segment display using CD4026 decade counter.", ["CD4026 Decade Counter IC", "7-Segment Common Cathode Display", "Resistor 220Ω (7x, segment resistors)", "Push button (clock)", "Resistor 10kΩ (pull-up)", "Capacitor 0.1µF (2x, debounce and bypass)", "5V Power Supply", "Breadboard"], ["CD4026 pin 16 (VDD) to 5V, pin 8 (VSS) to GND", "Clock input (pin 1) to push button with 10kΩ pull-up", "0.1µF debounce capacitor on clock input", "Display segments a-g to CD4026 pins: a-9, b-10, c-11, d-12, e-13, f-14, g-15", "Each segment pin through 220Ω to display", "Display common cathode to GND", "0.1µF bypass capacitor across power", "Pin 2 (enable) to GND, pin 3 (reset) to GND"], "CD4026 is a decade counter with built-in 7-segment decoder/driver. It counts from 0 to 9 and resets. Each clock pulse advances the count by one. 220Ω resistors limit LED segment current. The display shows the current count value (0-9). Multiple 4026s can be cascaded for multi-digit counting."),
    ("Traffic Light Controller using 4017", "Sequential traffic light (Red-Yellow-Green) using 4017 decade counter and diodes.", ["CD4017 Decade Counter IC", "555 Timer IC", "Resistor 100kΩ", "Resistor 10kΩ", "Capacitor 10µF", "Capacitor 0.1µF", "Diode 1N4148 (8x)", "Red LED", "Yellow LED", "Green LED", "Resistor 220Ω (3x, LED current)", "5V Power Supply", "Breadboard"], ["Wire 555 as astable: pin 8,4 to 5V; pin 1 to GND", "10kΩ between pin 7 and VCC", "100kΩ pot between pins 7 and 6", "10µF from pin 2 to GND", "555 pin 3 to 4017 pin 14 (clock)", "4017 pin 16 to 5V, pin 8 to GND", "Connect outputs via steering diodes to LEDs", "Q0 (pin 2) + Q1 (pin 4) to Red LED through diodes", "Q2 (pin 7) + Q3 (pin 10) to Yellow LED through diodes", "Q4 (pin 1) through Q9 to Green LED through diodes", "Each LED through 220Ω to GND"], "The 4017 decade counter activates one output at a time. Diodes combine outputs: Q0-Q1 = Red (2 clock cycles), Q2-Q3 = Yellow (2 cycles), Q4-Q9 = Green (6 cycles). The 555 provides adjustable clock speed. This mimics a real traffic light sequence with proper timing ratios."),
    # Op-Amp Circuits
    ("Inverting Amplifier using LM358", "Basic inverting op-amp amplifier with adjustable gain for signal processing.", ["LM358 Op-Amp IC", "Resistor 10kΩ (Rin)", "Resistor 100kΩ (Rf, sets gain = 10)", "Resistor 10kΩ (bias)", "Capacitor 10µF (2x, power supply filtering)", "Dual Power Supply ±5V", "Signal input source", "Breadboard", "Jumper wires"], ["LM358 pin 8 to +5V, pin 4 to -5V", "10µF capacitors from each supply pin to GND", "Non-inverting input (pin 3) to GND through 10kΩ", "Input signal to 10kΩ resistor (Rin) to inverting input (pin 2)", "100kΩ feedback resistor (Rf) from output (pin 1) to pin 2", "Apply input signal through input capacitor if AC coupling needed", "Measure output between pin 1 and GND"], "Gain = -Rf/Rin = -100k/10k = -10. The output is 180° out of phase with input. For a 0.5V input, output = -5V. Circuit bandwidth depends on gain-bandwidth product (1MHz for LM358). Useful for sensor signal amplification and audio preamplification."),
    ("Non-Inverting Amplifier", "Simple non-inverting amplifier using LM358 with positive gain.", ["LM358 Op-Amp IC", "Resistor 10kΩ (R1)", "Resistor 100kΩ (Rf)", "Capacitor 10µF (2x)", "Dual Power Supply ±5V", "Signal input", "Breadboard", "Jumper wires"], ["LM358 pin 8 to +5V, pin 4 to -5V", "10µF capacitors on supply pins", "Input signal to non-inverting input (pin 3)", "10kΩ (R1) from inverting input (pin 2) to GND", "100kΩ (Rf) from output (pin 1) to inverting input (pin 2)", "Measure output between pin 1 and GND"], "Gain = 1 + Rf/R1 = 1 + 100k/10k = 11. The output is in phase with the input. Input impedance is very high (MΩ range). For 0.5V input, output = 5.5V. This circuit is commonly used for sensor buffering and signal conditioning."),
    ("Active Low-Pass Filter", "Second-order Sallen-Key low-pass filter using LM358 for signal filtering.", ["LM358 Op-Amp IC", "Resistor 10kΩ (2x)", "Capacitor 0.1µF (2x)", "Capacitor 10µF (2x)", "Dual Power Supply ±5V", "Signal input", "Breadboard", "Jumper wires"], ["Design for cutoff frequency: fc = 1/(2×π×R×C) = 1/(2×π×10k×0.1µF) ≈ 159Hz", "Connect input to first 10kΩ resistor", "First resistor to second 10kΩ resistor", "First capacitor (0.1µF) from junction of resistors to GND", "Second capacitor (0.1µF) from second resistor end to op-amp output", "Both capacitors meet at op-amp output", "Non-inverting input to junction of second resistor and second capacitor", "Inverting input to output (buffer configuration)", "Op-amp pin 8 to +5V, pin 4 to -5V"], "The Sallen-Key topology provides a 2nd order (-40dB/decade) low-pass response. With equal resistors (10kΩ) and capacitors (0.1µF), cutoff is ~159Hz with Butterworth response (maximally flat). Above cutoff, signals attenuate sharply. Ideal for audio crossover and anti-aliasing filters."),
    # Alarm & Security
    ("PIR Motion Sensor Alarm", "Motion activated alarm using PIR sensor HC-SR501 and buzzer.", ["PIR Sensor HC-SR501", "NPN Transistor BC547", "Buzzer 5V", "Resistor 10kΩ", "Resistor 1kΩ", "Capacitor 10µF", "LED (status indicator)", "Resistor 220Ω", "5V Power Supply", "Breadboard"], ["HC-SR501 VCC to 5V, GND to GND", "PIR output to BC547 base through 10kΩ resistor", "BC547 collector to 5V through 1kΩ + buzzer", "LED with 220Ω from collector to GND", "BC547 emitter to GND", "10µF capacitor across PIR power for stability", "Adjust PIR sensitivity and time via onboard pots", "Test: walk in front of sensor within 3-7m range"], "PIR sensor detects infrared radiation changes from moving human body (warmth). When motion detected, output goes HIGH (3.3V) for adjustable duration. BC547 transistor drives the buzzer and LED. Detection range is 3-7 meters, 110° cone angle. Time delay adjustable from 5 seconds to 5 minutes."),
    ("Laser Security System", "Laser beam break detection alarm using LDR and laser module.", ["Laser Diode Module (5V, <5mW)", "LDR (Light Dependent Resistor)", "LM358 Op-Amp", "Resistor 10kΩ (2x)", "Potentiometer 100kΩ (threshold adjust)", "Buzzer 5V", "NPN Transistor BC547", "Resistor 1kΩ", "LED (status)", "5V Power Supply", "Breadboard"], ["LM358 as comparator: non-inverting (pin 3) to voltage divider (LDR + 10kΩ)", "LDR to 5V, 10kΩ to GND, junction to pin 3", "Inverting (pin 2) to potentiometer wiper (threshold)", "Potentiometer between 5V and GND", "LM358 output (pin 1) to BC547 base through 1kΩ", "BC547 collector to buzzer and LED", "BC547 emitter to GND", "Laser aimed at LDR from across room", "When beam breaks, LDR resistance increases → triggers alarm"], "LDR resistance is low (~1kΩ) when laser hits it, so voltage at pin 3 is low. When beam breaks, LDR resistance rises to ~1MΩ, voltage at pin 3 rises above threshold, LM358 output goes HIGH, triggering the buzzer. Threshold pot sets sensitivity."),
    ("Water Level Indicator", "Multi-level water tank indicator using transistor switches and LEDs.", ["NPN Transistor BC547 (4x)", "Resistor 470Ω (4x, LED current)", "Resistor 10kΩ (4x, base resistors)", "LED Red (empty)", "LED Yellow (low)", "LED Blue (medium)", "LED Green (full)", "Buzzer 5V (overflow alarm)", "5V Power Supply", "Probe wires (copper, different lengths)", "Breadboard"], ["Place probes at different heights in tank: lowest = empty, highest = full", "Each probe to base of each BC547 via 10kΩ resistor", "Transistor emitters to GND", "Collector of each transistor to respective LED via 470Ω", "LEDs to 5V", "Add buzzer from highest probe transistor collector to 5V", "Common probe at bottom of tank to 5V through 1MΩ", "Water completes circuit between common probe and level probes"], "When water touches a probe wire, it conducts (water has minerals making it slightly conductive). The BC547 transistor switches ON, lighting the corresponding LED. Multiple LEDs can be ON simultaneously showing exact water level. The highest probe triggers buzzer for overflow warning."),
    ("Rain Alarm Circuit", "Simple rain detector using sensing pad and transistor switch.", ["NPN Transistor BC547 (2x)", "Sensor grid (bare copper wires on PCB)", "Resistor 10kΩ", "Resistor 1kΩ", "Buzzer 5V", "LED (indicator)", "Resistor 220Ω", "Capacitor 10µF", "9V Battery", "Breadboard"], ["Create sensor grid: interleaved copper traces on small PCB", "Sensor grid one side to 9V through 10kΩ resistor", "Sensor grid other side to first BC547 base", "First BC547 collector to second BC547 base", "Second BC547 collector to buzzer and LED via resistor", "Both transistor emitters to GND", "Capacitor across sensor for debounce", "Test: drop water on sensor grid"], "Rain water (containing minerals) bridges the sensor grid traces, completing the circuit. The first BC547 amplifies this small current and drives the second transistor (Darlington pair configuration) which activates the buzzer and LED. High gain allows detection even with minimal water. Useful for automatic window closing or garden monitoring."),
    ("Touch Switch Circuit", "Touch-activated switch using transistor pair without moving parts.", ["NPN Transistor BC547 (2x)", "Resistor 100kΩ", "Resistor 1kΩ", "LED", "Resistor 220Ω", "Capacitor 0.1µF", "5V Power Supply", "Touch plate (copper or aluminum)", "Breadboard"], ["Connect touch plate to first BC547 base", "First BC547 collector to 100kΩ resistor to supply", "First BC547 emitter to GND", "Second BC547 base to first collector", "Second BC547 collector to LED via 220Ω to supply", "Second BC547 emitter to GND", "Capacitor from second base to GND (noise filtering)", "Touch the plate briefly to turn LED ON", "Touch again to turn OFF"], "The circuit forms a bistable multivibrator (flip-flop) using two transistors. When you touch the plate, your body's capacitance triggers the first transistor, changing the state. The circuit latches in one state until touched again. Each touch toggles the output. Ideal for touch-sensitive lamps or switches."),
    # Communication & IoT
    ("Bluetooth Controlled LED using HC-05", "Control LEDs wirelessly via smartphone Bluetooth using HC-05 module.", ["HC-05 Bluetooth Module", "Arduino Uno", "LED (2x, different colors)", "Resistor 220Ω (2x)", "Resistor 1kΩ (HC-05 voltage divider)", "Resistor 2kΩ (HC-05 voltage divider)", "5V Power Supply", "Breadboard", "Jumper wires"], ["HC-05 VCC to 5V, GND to GND", "HC-05 TX to Arduino RX (pin 0)", "HC-05 RX to Arduino TX (pin 1) through voltage divider (1k+2kΩ)", "Arduino pin 9 to first LED via 220Ω", "Arduino pin 10 to second LED via 220Ω", "Upload Serial Bluetooth code with SoftwareSerial", "Pair with smartphone (PIN 1234)", "Send '1' for LED1 ON, '2' for OFF, '3' for LED2 ON, '4' for OFF"], "HC-05 operates as serial-to-Bluetooth bridge. The voltage divider (1kΩ+2kΩ) drops Arduino 5V TX to 3.3V for HC-05 RX. Smartphone Serial Bluetooth Terminal app sends commands. The Arduino reads serial data and controls LEDs accordingly. Range is about 10 meters."),
    ("ESP8266 Wi-Fi Temperature Monitor", "IoT temperature monitoring using ESP8266 and LM35 with web dashboard.", ["ESP8266 NodeMCU", "LM35 Temperature Sensor", "Resistor 10kΩ", "Breadboard", "5V Power Supply", "Jumper wires"], ["ESP8266 VIN to 5V, GND to GND", "LM35 VCC to 3.3V (ESP output), GND to GND", "LM35 output to ESP8266 A0", "Connect ESP to WiFi: WiFi.begin('SSID', 'password')", "Start web server on port 80", "Read analog: temp = analogRead(A0) * 3.3 / 1024 * 100", "Create HTML page with auto-refresh showing temperature", "Access ESP IP address from browser"], "ESP8266 connects to WiFi network and runs a simple web server. LM35 provides analog voltage proportional to temperature. ESP reads ADC, converts to Celsius, and displays on a web page that auto-refreshes every few seconds. Can be expanded to control relays from the web interface."),
    # Measurement & Test Equipment
    ("Logic Probe Circuit", "Digital logic probe indicating HIGH, LOW, or PULSE states using LEDs.", ["NPN Transistor BC547 (2x)", "PNP Transistor BC557", "LED Red (HIGH indicator)", "LED Green (LOW indicator)", "LED Yellow (PULSE indicator)", "Resistor 220Ω (3x)", "Resistor 10kΩ (2x)", "Resistor 100kΩ", "Diode 1N4148 (2x)", "Capacitor 0.1µF", "Probe tip (needle or stiff wire)", "5V Power Supply"], ["Probe tip to 100kΩ to both transistor bases", "BC547 (NPN) base to probe via 10kΩ, collector to Red LED via 220Ω to 5V", "BC557 (PNP) base to probe via 10kΩ, collector to Green LED via 220Ω to GND", "Pulse detector: both transistors drive Yellow LED through diodes", "Capacitor from probe to GND for noise filtering", "5V supply to probe reference ground", "Test: touch probe to 5V → Red ON, to GND → Green ON, toggling → Yellow", "Battery clip with 9V for portable use"], "When probe touches a HIGH (logic 1) signal, BC547 turns ON lighting Red LED. When LOW (logic 0), BC557 turns ON lighting Green LED. Rapid toggling (pulse) activates both briefly, lighting Yellow LED. Essential tool for debugging digital circuits without an oscilloscope."),
    ("Component Tester (ESR Meter)", "Simple ESR meter for testing electrolytic capacitors using 555 timer.", ["555 Timer IC", "Resistor 1kΩ", "Resistor 10kΩ", "Potentiometer 10kΩ (calibration)", "Capacitor 0.1µF", "Capacitor 10µF", "Capacitor 100µF (known good for calibration)", "Diode 1N4148 (2x)", "Microammeter or multimeter (mV range)", "5V Power Supply", "Test probes"], ["Wire 555 as astable multivibrator at ~50kHz", "R1=1kΩ, R2=10kΩ, C=0.1µF", "555 output to capacitor under test through 1kΩ limiting resistor", "Rectify output using diodes and filter capacitor", "Connect microammeter across test capacitor", "Calibrate with known good 100µF capacitor", "Test unknown capacitors: higher reading = higher ESR", "Safe discharge all capacitors before testing"], "ESR (Equivalent Series Resistance) is a measure of capacitor health. High ESR indicates aging/drying electrolyte. This circuit applies a 50kHz AC signal to the capacitor and measures the voltage drop across its ESR. Good capacitors show near-zero reading; bad capacitors show high readings. Typical good ESR for 100µF: <1Ω."),
    # Raspberry Pi Projects
    ("Raspberry Pi GPIO LED Blink", "Control GPIO pins to blink LED from Raspberry Pi using Python.", ["Raspberry Pi (any model)", "LED", "Resistor 330Ω", "Breadboard", "Male-female jumper wires"], ["Connect LED anode (long leg) to GPIO 17 (pin 11)", "Connect LED cathode through 330Ω resistor to GND (pin 6)", "Install RPi.GPIO library", "Write Python script: import RPi.GPIO as GPIO; GPIO.setmode(GPIO.BCM); GPIO.setup(17, GPIO.OUT)", "GPIO.output(17, GPIO.HIGH) for ON, LOW for OFF", "Run with sudo: sudo python3 blink.py", "Use time.sleep(1) for 1 second interval"], "Raspberry Pi GPIO pins are 3.3V logic. The 330Ω resistor limits LED current to safe ~10mA. GPIO 17 is one of the general-purpose pins that can be set as output. Python's RPi.GPIO library provides simple control. Always use a resistor to protect both LED and GPIO pin."),
    ("Raspberry Pi Temperature and Humidity Sensor", "Read DHT11/DHT22 sensor data from Raspberry Pi and log to file.", ["Raspberry Pi", "DHT11 Temperature/Humidity Sensor", "Resistor 10kΩ (pull-up)", "Breadboard", "Female-female jumper wires"], ["DHT11 pin 1 to 3.3V (pin 1 on Pi)", "DHT11 pin 2 to GPIO 4 (pin 7)", "10kΩ pull-up resistor from pin 2 to 3.3V", "DHT11 pin 4 to GND (pin 6 on Pi)", "Install Adafruit_DHT: pip install Adafruit_DHT", "Write Python script to read sensor every 2 seconds", "Log data with timestamp to CSV file", "Plot data using matplotlib for visualization"], "DHT11 uses single-wire protocol to send temperature (°C) and humidity (%) data. Accuracy: ±2°C, ±5% RH. Range: 0-50°C, 20-80% RH. The 10kΩ pull-up keeps the data line HIGH. Read interval must be at least 1 second (DHT11 is slow). DHT22 provides better accuracy (±0.5°C, ±2% RH) and wider range."),
    # Arduino Advanced
    ("Arduino OLED Display", "Display text and graphics on 0.96-inch SSD1306 OLED display with Arduino.", ["Arduino Uno", "SSD1306 OLED Display (128x64, I2C)", "Breadboard", "Jumper wires"], ["OLED VCC to Arduino 5V", "OLED GND to Arduino GND", "OLED SCL to Arduino A5 (SCL)", "OLED SDA to Arduino A4 (SDA)", "Install libraries: Adafruit_SSD1306, Adafruit_GFX", "Initialize: display.begin(SSD1306_SWITCHCAPVCC, 0x3C)", "Use display.print() for text, display.drawPixel() for graphics", "display.display() to update screen"], "SSD1306 OLED uses I2C protocol for communication. Resolution: 128×64 pixels. I2C address is typically 0x3C or 0x3D. The display doesn't require backlight (OLED is emissive). Adafruit libraries provide text, shapes, and bitmap drawing functions. Refresh rate: up to 30fps for simple graphics."),
    ("Arduino Keypad Lock", "4x4 matrix keypad electronic lock with relay output using Arduino.", ["Arduino Uno", "4x4 Matrix Keypad", "Relay Module (5V)", "LED Green (unlock)", "LED Red (locked)", "Resistor 220Ω (2x)", "Buzzer (key press feedback)", "12V Solenoid Lock (optional)", "5V/12V Power Supply", "Breadboard"], ["Connect keypad rows to Arduino D8-D11", "Keypad columns to D4-D7", "Relay module IN to D12", "Green LED to D2 via 220Ω", "Red LED to D3 via 220Ω", "Buzzer to D13 via 1kΩ", "Set password: e.g. '1234' in code", "On correct password: activate relay for 3 seconds", "On wrong password: increment attempt counter, lock for 10s after 3 attempts", "Add EEPROM storage for persistent password"], "Matrix keypad uses row-column scanning to detect key presses. The relay module can control high-voltage devices (solenoid lock, door strike). The Arduino compares entered code against stored password. Anti-tamper feature locks out after multiple wrong attempts. EEPROM stores password persistently."),
    # Specialized Audio
    ("LED Audio Spectrum Analyzer", "Audio level display using LM3915 dot/bar display driver IC.", ["LM3915 LED Bar Graph Driver", "Electret Microphone", "Resistor 1kΩ", "Resistor 10kΩ", "Capacitor 1µF (2x)", "Capacitor 0.1µF", "LED (10x, different colors recommended)", "Resistor 220Ω (10x)", "Potentiometer 10kΩ (gain adjust)", "5V Power Supply", "Breadboard"], ["LM3915 pin 3 to 5V, pin 2 to GND", "Audio input to pin 5 through 1µF capacitor", "10kΩ pot from pin 5 to GND (gain control)", "Pin 7 (REF ADJ) to GND through 1kΩ", "Pin 6 to pin 7 through 1kΩ", "Pin 8 (REF OUT) to +5V through 1kΩ", "LEDs from pins 1,18 through 10 to GND via 220Ω each", "Pin 9 set: to VCC for bar mode, float for dot mode", "0.1µF across power supply"], "LM3915 is a logarithmic LED driver with 3dB/step suitable for audio. 10 LEDs cover a 30dB dynamic range. The internal voltage reference creates precision thresholds. Dot mode shows only one LED at a time (like VU meter); bar mode shows cumulative levels. Ideal for audio level monitoring and peak indicators."),
    # Power Electronics
    ("12V to 5V USB Charger using LM2596", "Efficient buck converter for 5V 3A output from 12V input using LM2596.", ["LM2596 Buck Converter Module", "Capacitor 220µF 25V (input)", "Capacitor 220µF 16V (output)", "USB Type-A Female Socket", "12V Power Supply", "LED (power indicator)", "Resistor 1kΩ (LED)", "Multimeter for calibration"], ["Connect 12V input to LM2596 IN+ and IN-", "220µF 25V capacitor across input terminals", "220µF 16V capacitor across output terminals", "Connect USB socket: D+ and D- can be left open for charging only", "USB VBUS to output positive, GND to negative", "LED with resistor across output (polarity correct)", "Adjust trimmer pot while measuring output for exactly 5.00V", "Do NOT exceed 3A continuous load"], "LM2596 is a step-down (buck) switching regulator with up to 90% efficiency. Unlike linear regulators (like 7805), it doesn't waste excess voltage as heat. Output voltage is adjustable from 1.25V to 37V via the trimmer pot. At 3A output, a heat sink may be needed. Input should be at least 1.5V higher than output voltage."),
    # Fun & Educational
    ("Electronic Dice using 4017", "Random number generator (1-6) using 4017 IC and 555 timer for dice game.", ["555 Timer IC", "CD4017 Decade Counter", "LED (6x, arranged as dice face)", "Resistor 100kΩ", "Resistor 10kΩ", "Capacitor 10µF", "Capacitor 0.1µF", "Resistor 220Ω (6x)", "Push button (roll)", "9V Battery", "Breadboard"], ["555 astable: pin 8 to VCC, pin 1 to GND", "10kΩ between pins 7 and 8", "100kΩ pot between pins 6 and 7", "10µF from pin 2 to GND", "555 pin 3 to 4017 pin 14 (clock)", "4017 outputs Q0-Q5 (pins 2,4,7,10,1,5) to 6 LEDs via 220Ω", "Arrange LEDs in dice pattern: 2-3-1-4-6-5", "Push button from VCC to 555 pin 4 (RESET)", "Button released: fast counting; button pressed: stop and show value", "0.1µF across power"], "When the button is pressed, RESET pin goes HIGH stopping the 555 oscillator. The count stops at that position showing a random dice value (1-6). The circuit cycles through thousands of counts per second, so the result is effectively random. LEDs arranged in standard dice pattern for authentic feel."),
    ("LED Cube 3x3x3", "3D LED cube with 27 LEDs controlled by Arduino via multiplexing.", ["Arduino Uno", "LED (27x, same color)", "Resistor 220Ω (9x, column resistors)", "NPN Transistor BC547 (3x, layer control)", "Resistor 10kΩ (3x, base resistors)", "Breadboard (for controller)", "Perfboard (for cube)", "5V Power Supply", "Jumper wires"], ["Build LED cube: 3 layers × 9 LEDs each on perfboard", "All LED anodes in same column connect together (9 columns)", "All LED cathodes in same layer connect together (3 layers)", "Column wires to Arduino D2-D10 via 220Ω resistors", "Layer wires to BC547 collectors", "BC547 bases to Arduino D11-D13 via 10kΩ", "BC547 emitters to GND", "Write multiplexing code: scan layers at >60Hz for flicker-free", "Create animation patterns (rain, snake, blink, rotate)"], "Multiplexing turns on one layer at a time while enabling only the LEDs needed in that layer. By scanning all layers rapidly (>60Hz), persistence of vision makes all lit LEDs appear simultaneously. Power: at most 9 LEDs ON at once (3 per layer × 3 layers), keeping current within limits. Complex patterns can be stored in PROGMEM."),
]

import json

def generate_entry(title, desc, components, wiring, explanation):
    """Format a circuit entry as Python dict string."""
    return json.dumps({
        "title": title,
        "type": "circuit_generation",
        "description": desc,
        "components": components,
        "wiring_steps": wiring,
        "explanation": explanation,
        "circuit_diagram_description": title.lower() + " wiring diagram with all components connected as described.",
        "sources": [
            {"name": "Wikipedia - Electronics", "url": "https://en.wikipedia.org/wiki/Electronics"},
            {"name": "Electronics Tutorials", "url": "https://www.electronics-tutorials.ws"},
        ],
    }, indent=4) + ","


if __name__ == "__main__":
    entries = []
    for title, desc, components, wiring, explanation in CIRCUITS:
        entries.append(generate_entry(title, desc, components, wiring, explanation))

    output = "\n".join(entries)
    print(f"Generated {len(CIRCUITS)} circuit entries")
    print(f"\n--- PASTE BELOW INTO sources.py before the closing ']' ---\n")
    print(output)
