apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: breadboard-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: api.breadboard.ai
      http:
        paths:
          - path: /v1(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: breadboard-backend
                port:
                  number: 8000
          - path: /ai(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: breadboard-ai-engine
                port:
                  number: 8001
