name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install flake8 black
      - run: cd backend && flake8 app tests
      - run: cd ai-engine && flake8 engine tests
      - uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
